### NumPy Array Vs Python Lists

We use Python NumPy array instead of a list because of the below two reasons:

* Less Memory Fast Convenient: The very first reason to choose Python NumPy array is that it occupies less memory as compared to list.
* Then, it is pretty fast in terms of execution.


In [1]:
import numpy as np

#### Introduction to NumPy Arrays

In [21]:
a = np.arange(24) # returns a one dimensional array. The number of square brackes tells you the 
#dimension of the array.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
a.ndim # to check for the dimension of our array

1

In [23]:
k = a.reshape(2, 12) #to change the dim of the array
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [24]:
k.ndim

2

In [25]:
b = np.arange(36).reshape((3, 3, 4))
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [26]:
b.ndim

3

In [27]:
a.ndim

1

In [28]:
a.shape

(24,)

In [29]:
a.size

24

In [30]:
a.dtype

dtype('int32')

In [31]:
a.itemsize # memory size

4

In [2]:
group = np.array([[29, 10, 40], [45, 9, 30], [34, 5, 35], [38,4, 35]])
group

array([[29, 10, 40],
       [45,  9, 30],
       [34,  5, 35],
       [38,  4, 35]])

In [3]:
group.shape

(4, 3)

In [4]:
group.ndim

2

In [5]:
group[2]

array([34,  5, 35])

In [6]:
group[0]

array([29, 10, 40])

In [7]:
persons_data = [[29, 10, 40], ###Nested list
               [45, 9, 30],
               [34, 5, 35],
               [38, 4, 35]]
persons_data

[[29, 10, 40], [45, 9, 30], [34, 5, 35], [38, 4, 35]]

In [37]:
persons_data[3]

[38, 4, 35]

In [38]:
persons_data.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
numpy_group = np.array(persons_data) ### Making persons_data an array
numpy_group

In [ ]:
numpy_group.shape ###Returns the shape in rows and columns

In [ ]:
numpy_group[:,0] ##All the rows and column one

In [ ]:
numpy_group[0,:] ##All the columns in row one

In [ ]:
numpy_group.mean()

In [ ]:
numpy_group[1:3,1:] #Row one to three(1:3, excluding row 3), column one to the end

In [ ]:
numpy_group[2,1:]

In [ ]:
numpy_group[1,0]

### 28/07/2021

In [ ]:
numpy_group.mean(axis = 0) ### Vertical mean along y-axis

In [ ]:
numpy_group.mean(axis = 1)

#### Special Types Of Arrays

In [ ]:
np.zeros(6)

In [ ]:
np.zeros(6).reshape(2,3)

In [ ]:
np.zeros(6).reshape(3,3)

In [ ]:
np.ones(18)

In [ ]:
np.ones(18).reshape(3,6)

In [ ]:
np.ones((3,6))

In [ ]:
np.full((3, 6), 23)

In [ ]:
np.random.random((3,6)) ##returns random numbers with 3 rows and 6 columns...

#### The Arrange Method

In [ ]:
np.arange(0,20,5) ## The starting, stopping and stepping argument

In [ ]:
numpy_group

In [ ]:
numpy_group.ndim

In [ ]:
numpy_group[0]

In [ ]:
numpy_group[0,2]

In [ ]:
numpy_group

In [ ]:
numpy_group[0] = [30, 11, 1400]
numpy_group

In [ ]:
numpy_group[:2] ###Subset index 0 and 1

In [ ]:
numpy_group[2:]

In [ ]:
numpy_group[:-3]

In [ ]:
numpy_group[-3:] #Reverse of 3, starts indexing reversely

In [ ]:
numpy_group[0:4:2]

In [ ]:
numpy_group[::-1] ##Reversing your array

In [ ]:
numpy_group[0:3,1:3] ###Rows 1-3, columns 1 to 3

In [ ]:
numpy_group

In [ ]:
numpy_group[:,2]

In [ ]:
numpy_group[0:3:2, ::-122]

### Manipulating Numpy Arrays with Operators and Aggregate Fxns


#### Basic Operators

In [ ]:
numpy_group

In [ ]:
numpy_group + 1

In [ ]:
numpy_group / 1

In [ ]:
numpy_group // 10

In [ ]:
numpy_group / 10

In [ ]:
numpy_group * 2

In [ ]:
### Adding two arrays of the same shape
numpy_group + numpy_group

In [ ]:
numpy_group - numpy_group

### Comparism Operators

In [ ]:
numpy_group

In [ ]:
numpy_group > 30

In [ ]:
numpy_group < 50

In [ ]:
numpy_group == 38

In [ ]:
numpy_group >= 11

### Logical Operators 

In [ ]:
### The and operator

(numpy_group >30) & (numpy_group <=35)

In [ ]:
### the or operator
(numpy_group <= 30)|(numpy_group > 35)

In [ ]:
### The negation operator
~(numpy_group <= 30) | (numpy_group >35)

### Adding and Removing Elements from NumPy Arrays

* Append horizontally and vertically
* Vertical stacking, 
* Insert, and
* Delete

#### Append

In [ ]:
a = np.arange(24).reshape(2,3,4)
a

In [ ]:
b = np.append(a,[5, 6, 7, 8])
b

In [ ]:
b.shape

In [ ]:
b.reshape(7,4)

In [ ]:
c = np.array(np.arange(24)).reshape(2,3,4)*10 + 3
c

In [ ]:
### Joining along the row(axis = 0)

np.append(a, c, axis = 0)

In [ ]:
np.append(a, c, axis = 0).shape

In [ ]:
## Joining along the column (axis = 1)

In [ ]:
np.append(a, c, axis = 1)

In [ ]:
np.append(a, c, axis = 1).shape

In [ ]:
np.append(a, c, axis = 2)

In [ ]:
np.append(a, c, axis = 2).shape

### Hstack

In [ ]:
a

In [ ]:
c

In [ ]:
my_num = np.hstack((a,c))
my_num

In [ ]:
my_num[0,0,2] = 999 ###array 1, row 1, column 3
my_num

In [ ]:
after_insert_array = np.insert(a, 1, 444, axis = 0) 
after_insert_array

In [ ]:
after_insert_array = np.insert(c, 1, 444, axis = 1)
after_insert_array

In [ ]:
after_insert_array = np.insert(c, 1, 444, axis = 2)
after_insert_array

In [ ]:
c.shape

In [ ]:
d = np.empty(c.shape)
#int(d)
d

In [ ]:
np.copyto(d,c)
d

In [ ]:
print(d)
print(c)

In [ ]:
np.delete(d, 1, axis = 0)

In [ ]:
np.delete(d, 1, axis = 1)

In [ ]:
np.delete(d,1, axis = 2)

### Joining and splitting arrays

#### Concatenate, Stack and Split

In [ ]:
a = np.array([1, 2, 3, 4]).reshape(2,2)
b = np.array([[5, 6]])
print(a)
print(b)

In [ ]:
together = np.concatenate((a, b), axis = 0)
together

In [ ]:
together.shape

In [ ]:
together[2,1] = 55
together

In [ ]:
a

In [ ]:
c = np.array([[1, 2], [3,4]])*3+5
c

In [ ]:
np.concatenate((a, c), axis = 0)

In [ ]:
np.concatenate((a,c), axis = 1)

In [ ]:
np.concatenate((a, c), axis = 2) ## Will return wrong becos the two(a and c) arrays are dimensional 
##and axis = 2 is including a third dimension which the array doesn't have

#### Rearranaging Array Elements

In [ ]:
first = np.array(np.arange(24))
second = first.reshape(3,8)
third = second.reshape(2, 3, 4) ## a three dimensional array

In [ ]:
first

In [ ]:
second

In [ ]:
third

#### Flip Left to Right

In [ ]:
np.fliplr(second)

In [ ]:
np.fliplr(third)

#### Flip Up and Down

In [ ]:
np.flipud(third)

In [ ]:
np.roll(first, 5)

In [ ]:
np.roll(first, -5)

In [ ]:
np.roll(third, 2)

In [ ]:
second

In [ ]:
np.rot90(second)

In [ ]:
np.rot90(second, k = -1)

#### Splitting

In [ ]:
temp  = np.arange(6)
temp

In [ ]:
np.split(temp, 2)

In [ ]:
np.split(temp, 3)

#### Views and Copies

In [ ]:
first_array = np.array([-45, -31, -12, 0, 25, 51, 99])
first_array

In [ ]:
price = np.array(["pea", 45, "mango", 78, "orange", 70, "sugarcane", 30])
price

In [ ]:
len(price)

In [ ]:
for i in price:
    print(len(i)) 

In [ ]:
length_checker = np.vectorize(len) ###vectorize is to reduce computational time

In [ ]:
length_checker(price)

In [ ]:
np.vectorize(len)(price)

In [ ]:
price[2]

In [ ]:
price[2] = "banana"
price

In [ ]:
price[-2] = "apple"
price

In [ ]:
first_array

In [ ]:
second_array = first_array
second_array

#### Same or Different?

In [ ]:
first_array is second_array

In [ ]:
first_array == second_array

### Doing Copy Methods


#### Method 1:View()

In [ ]:
my_array = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [ ]:
my_array_copy = my_array.view()

In [ ]:
my_array_copy

In [ ]:
my_array_copy.shape

In [ ]:
my_array_copy.shape = (2, 4)
my_array_copy

#### Transpose-Like Operations

In [ ]:
first

In [ ]:
second = first.reshape(3, 8)
second

In [ ]:
third = second.reshape(2, 3, 4)
third

In [ ]:
first_trans = np.transpose(first)
first_trans

In [ ]:
print(first.shape)
print(first_trans.shape)

In [ ]:
second

In [ ]:
second_trans = np.transpose(second)
second_trans

In [ ]:
print(second.shape)
print(second_trans.shape)

In [ ]:
third_trans = np.transpose(third)
third_trans

In [ ]:
print(third.shape)
print(third_trans.shape)

#### np.transpose(third)

In [ ]:
third_trans = np.transpose(third, axes = (0, 2, 1))
third_trans

In [ ]:
 print(third_trans.shape)

### NOTE: 
The axes parameter represents the positioning of the shape of the array. Initially our array is of the **form(shape)(2,3,4)** which means thta the initial axes is by default **(0, 1, 2)** . Transposing it with the **axes=(0,2,1)** implies the transpose fxn should make our second axis to be third and the third axis to be second, wch will return **(2,3,4)**.  

### Linear Algebra

To install the sympy library use the command below:

conda install  sympy

In [ ]:
conda install  sympy

In [ ]:
from sympy import init_session
init_session()

##Sympy is a python library for symbolic mathematics                 

## symPy uses Unicode characters to render output in form of pretty print. If you are using Python console for
#executing  SymPy session, the best pretty printing environment is activated by calling init_session() function

In [2]:
diff(x**3)

In [ ]:
diff(x**3, x, 2)

In [ ]:
diff((x**2-3*x + 5)**3, x, 2)